### ISSUE TITLE
list index out of range when trying to download input

### ISSUE THREAD

**Issue by GoogleCodeExporter** [soimort/codejam-commandline#17]
```
(It worked fine to download through the website)

krka@kristofer:~/dev/codejam/2012-04-14$ ./gcj_download_input.py D small 0
-------------------------------------------------------------------------------
Small input for "D - Hall of Mirrors" at "source/D-small.in"
-------------------------------------------------------------------------------
Getting status of contest 1460488 from "code.google.com"...
200 OK, 579 bytes read from server (1021 uncompressed).
Getting user status at contest 1460488 from "code.google.com"...
200 OK, 105 bytes read from server (168 uncompressed).
Traceback (most recent call last):
  File "./gcj_download_input.py", line 263, in <module>
    main()
  File "./gcj_download_input.py", line 208, in main
    problem_input_state = problem_inputs[problem_index][input_index]
IndexError: list index out of range

```

Original issue reported on code.google.com by `kristofer.karlsson@gmail.com` on 14 Apr 2012 at 10:35
- Merged into: #20

**Comment by GoogleCodeExporter** [comment]
```
We are aware of this issue, a fix is on the way.
```

Original comment by `jor...@google.com` on 9 Jun 2012 at 1:31
- Changed state: **Duplicate**
- Added labels: **Priority-Critical**, **OpSys-All**, **Usability**
- Removed labels: **Priority-Medium**
